// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {core} from '../models';

export function AddUrls(arg1:core.UrlsForm):Promise<core.ResData>;

export function DeleteUrlsByIds(arg1:core.IdsForm):Promise<core.ResData>;

export function GetAlbumList():Promise<core.ResData>;

export function GetSetting():Promise<core.SettingData>;

export function GetUrlsCount():Promise<number>;

export function GetUrlsList(arg1:core.UrlsList):Promise<core.ResData>;

export function UpdateSetting(arg1:core.SettingData):Promise<boolean>;

export function UpdateUrlsStatus(arg1:core.IdsStatus):Promise<core.ResData>;
