// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {core} from '../models';

export function AddScanTask(arg1:core.AddScanTaskParams):Promise<core.ResData>;

export function AddUrls(arg1:core.UrlsForm):Promise<core.ResData>;

export function DeleteTasks(arg1:core.DeleteTasksParams):Promise<core.ResData>;

export function DeleteUrlsByIds(arg1:core.IdsForm):Promise<core.ResData>;

export function ExportTaskURLS(arg1:number):Promise<core.ResData>;

export function ExportUrlsToCsv(arg1:core.ExportParams):Promise<core.ResData>;

export function GetAlbumList():Promise<core.ResData>;

export function GetAppInfo():Promise<core.ResData>;

export function GetRecentLogs():Promise<core.ResData>;

export function GetScanList(arg1:core.ScanListParams):Promise<core.ResData>;

export function GetScanTaskCount():Promise<number>;

export function GetSetting():Promise<core.SettingData>;

export function GetTotalPages():Promise<number>;

export function GetUrlsCount():Promise<number>;

export function GetUrlsList(arg1:core.UrlsList):Promise<core.ResData>;

export function RetryTask(arg1:number):Promise<core.ResData>;

export function SelectScanDirectory():Promise<string>;

export function UpdateSetting(arg1:core.SettingData):Promise<boolean>;

export function UpdateUrlsStatus(arg1:core.IdsStatus):Promise<core.ResData>;
