// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddUrls(arg1) {
  return window['go']['core']['AppCore']['AddUrls'](arg1);
}

export function DeleteUrlsByIds(arg1) {
  return window['go']['core']['AppCore']['DeleteUrlsByIds'](arg1);
}

export function GetAlbumList() {
  return window['go']['core']['AppCore']['GetAlbumList']();
}

export function GetSetting() {
  return window['go']['core']['AppCore']['GetSetting']();
}

export function GetUrlsCount() {
  return window['go']['core']['AppCore']['GetUrlsCount']();
}

export function GetUrlsList(arg1) {
  return window['go']['core']['AppCore']['GetUrlsList'](arg1);
}

export function UpdateSetting(arg1) {
  return window['go']['core']['AppCore']['UpdateSetting'](arg1);
}

export function UpdateUrlsStatus(arg1) {
  return window['go']['core']['AppCore']['UpdateUrlsStatus'](arg1);
}
