// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddScanTask(arg1) {
  return window['go']['core']['AppCore']['AddScanTask'](arg1);
}

export function AddUrls(arg1) {
  return window['go']['core']['AppCore']['AddUrls'](arg1);
}

export function DeleteTasks(arg1) {
  return window['go']['core']['AppCore']['DeleteTasks'](arg1);
}

export function DeleteUrlsByIds(arg1) {
  return window['go']['core']['AppCore']['DeleteUrlsByIds'](arg1);
}

export function ExportTaskURLS(arg1) {
  return window['go']['core']['AppCore']['ExportTaskURLS'](arg1);
}

export function ExportUrlsToCsv(arg1) {
  return window['go']['core']['AppCore']['ExportUrlsToCsv'](arg1);
}

export function GetAlbumList() {
  return window['go']['core']['AppCore']['GetAlbumList']();
}

export function GetAppInfo() {
  return window['go']['core']['AppCore']['GetAppInfo']();
}

export function GetRecentLogs() {
  return window['go']['core']['AppCore']['GetRecentLogs']();
}

export function GetScanList(arg1) {
  return window['go']['core']['AppCore']['GetScanList'](arg1);
}

export function GetScanTaskCount() {
  return window['go']['core']['AppCore']['GetScanTaskCount']();
}

export function GetSetting() {
  return window['go']['core']['AppCore']['GetSetting']();
}

export function GetTotalPages() {
  return window['go']['core']['AppCore']['GetTotalPages']();
}

export function GetUrlsCount() {
  return window['go']['core']['AppCore']['GetUrlsCount']();
}

export function GetUrlsList(arg1) {
  return window['go']['core']['AppCore']['GetUrlsList'](arg1);
}

export function RetryTask(arg1) {
  return window['go']['core']['AppCore']['RetryTask'](arg1);
}

export function SelectScanDirectory() {
  return window['go']['core']['AppCore']['SelectScanDirectory']();
}

export function UpdateSetting(arg1) {
  return window['go']['core']['AppCore']['UpdateSetting'](arg1);
}

export function UpdateUrlsStatus(arg1) {
  return window['go']['core']['AppCore']['UpdateUrlsStatus'](arg1);
}
