// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function GetMessage():Promise<string>;

export function GetRunDir(arg1:context.Context):Promise<string>;

export function Greet(arg1:string):Promise<string>;
